"""empty message

Revision ID: 136746344532
Revises: 4cddf2beea08
Create Date: 2020-12-19 18:27:37.886707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136746344532'
down_revision = '4cddf2beea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_time_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_time_total')
    # ### end Alembic commands ###
