"""empty message

Revision ID: 4cddf2beea08
Revises: 6a305d060d1e
Create Date: 2020-12-19 18:27:15.235644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cddf2beea08'
down_revision = '6a305d060d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_time_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_time_total', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
