"""empty message

Revision ID: 6a305d060d1e
Revises: eefc3277bfd6
Create Date: 2020-12-19 18:16:05.210655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a305d060d1e'
down_revision = 'eefc3277bfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_time_total', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_time_total')
    # ### end Alembic commands ###
