"""empty message

Revision ID: 6bba5015aa84
Revises: 3b1d4b45d817
Create Date: 2020-12-14 04:47:06.885304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bba5015aa84'
down_revision = '3b1d4b45d817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'signer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'signers', ['signer_id'], ['id'])
    # ### end Alembic commands ###
