"""empty message

Revision ID: 80527011480d
Revises: 92e4b4d3e0b3
Create Date: 2020-12-19 17:39:22.734571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80527011480d'
down_revision = '92e4b4d3e0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signers', 'sign_time_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signers', sa.Column('sign_time_total', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
