"""empty message

Revision ID: 92e4b4d3e0b3
Revises: a1668fcabc58
Create Date: 2020-12-18 22:41:11.916584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e4b4d3e0b3'
down_revision = 'a1668fcabc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signer_class', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('sign_time', sa.DateTime(), nullable=True),
    sa.Column('signout_time', sa.DateTime(), nullable=True),
    sa.Column('sign_time_total', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signers_name'), 'signers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signers_name'), table_name='signers')
    op.drop_table('signers')
    # ### end Alembic commands ###
