"""empty message

Revision ID: a1668fcabc58
Revises: fec34b6907da
Create Date: 2020-12-18 20:53:46.781647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1668fcabc58'
down_revision = 'fec34b6907da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signers', sa.Column('sign_time_total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signers', 'sign_time_total')
    # ### end Alembic commands ###
