"""empty message

Revision ID: b14f2c216931
Revises: 65f424727b01
Create Date: 2020-12-15 05:23:58.202897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b14f2c216931'
down_revision = '65f424727b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'signer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_2', 'users', 'signers', ['signer_id'], ['id'])
    # ### end Alembic commands ###
