"""empty message

Revision ID: eefc3277bfd6
Revises: 80527011480d
Create Date: 2020-12-19 18:15:34.250925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eefc3277bfd6'
down_revision = '80527011480d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_time_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_time_total', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
